---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "defectdojo-exporter.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.args.port }}
  selector:
    app: {{ include "defectdojo-exporter.name" . }}
